
name: PROD Test, build, release version and publish to NPM

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC trusted publishing
  contents: write  # Required for git push

jobs:

  build-test-release-and-publish-npm:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          registry-url: 'https://registry.npmjs.org'
      - run: git config --global user.email "igortrindademe@gmail.com"
      - run: git config --global user.name "Igor Trindade"
      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm run test
      - run: npm run build
      - run: npm run release --commit-all
      - run: git push --follow-tags origin ${{ github.ref_name }}
      - run: npm publish --access public
